### ISSUE TITLE
G should be G1

### ISSUE THREAD

**Issue by mukeshtiwari** [RareSkills/ZK-bulletproofs#2]
https://github.com/RareSkills/ZK-bulletproofs/blob/2b782b81f0d70039383fc2559813263ed16e6e8e/chapter-05.py#L82

**Comment by RareSkills** [comment]
This isn't correct, it's supposed to be a point with an unknown discrete log.

**Comment by mukeshtiwari** [comment]
Now I am slightly confused with this exercise. Yes, I agree that it should be a point -- and not a vector of points -- with an unknown discrete log with all the points (vector) **G** and (vector) **H**, but the point G in this equation t_uG + \pi_tB \stackrel{?}{=} V + T_1 u + T_2 u^2 is a single point.  Therefore, it is not type correct and if I use **G** I get this error 

```
Traceback (most recent call last):
  File "/Users/mukesh.tiwari/Mukesh/Github/ZK-bulletproofs/chapter-05.py", line 89, in <module>
    assert eq(add(multiply(G, t_u), multiply(B, pi_t)), add_points(V, multiply(T1, u), multiply(T2, u**2 % p))), "t_u not evaluated correctly"
  File "/Users/mukesh.tiwari/Mukesh/Github/ZK-bulletproofs/.venv/lib/python3.9/site-packages/py_ecc/bn128/bn128_curve.py", line 111, in multiply
    return add(multiply(double(pt), int(n // 2)), pt)
  File "/Users/mukesh.tiwari/Mukesh/Github/ZK-bulletproofs/.venv/lib/python3.9/site-packages/py_ecc/bn128/bn128_curve.py", line 77, in double
    x, y = pt
ValueError: too many values to unpack (expected 2)
```
(I can generate a point by following the drill in the second chapter, but is that also the exercise’s goal?).
